services:
  backend:
    build: .
    container_name: ecommerce
    ports:
      - "80:80"
    volumes:
      - ".:/var/www/html"
    networks:
      - app_network   

  postgres:
    image: postgres:latest   
    container_name: postgres_ecommerce
    environment:
       POSTGRES_PASSWORD: "root123"
       POSTGRES_USER: "root"
       POSTGRES_DB: "ecommerce"
    volumes:
      - pgdata:/var/lib/posgresql/data
    ports:
      - 5432:5432     
    networks:
      - app_network
volumes:
  pgdata:
networks:
  app_network:
    driver: bridge      


      
    
    